/**
 * SEMESTA ISLAM — Capability Catalog & Role Capability Matrix
 * Governed by MASTER_EXECUTION_PROMPT §12-13 (permission & scope model).
 *
 * Capabilities are stable string identifiers. A role grants a set of
 * capabilities within a scope. Authorization resolves at the server.
 */

import type { UserRole } from '@/types';
import type { OrganizationRole } from '@prisma/client';

export const CAPABILITIES = {
  // Organization
  ORGANIZATION_VIEW: 'organization.view',
  ORGANIZATION_UPDATE: 'organization.update',

  // Members
  MEMBERS_VIEW: 'members.view',
  MEMBERS_INVITE: 'members.invite',
  MEMBERS_UPDATE: 'members.update',
  MEMBERS_REMOVE: 'members.remove',

  // Roles & permissions
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',

  // Courses & programs
  COURSES_VIEW: 'courses.view',
  COURSES_MANAGE: 'courses.manage',
  PROGRAMS_VIEW: 'programs.view',
  PROGRAMS_MANAGE: 'programs.manage',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  // Bookings
  BOOKINGS_VIEW: 'bookings.view',
  BOOKINGS_MANAGE: 'bookings.manage',

  // Verification
  VERIFICATION_VIEW: 'verification.view',
  VERIFICATION_MANAGE: 'verification.manage',

  // Content & communications
  CONTENT_VIEW: 'content.view',
  CONTENT_MANAGE: 'content.manage',
  CONTENT_PUBLISH: 'content.publish',
  COMMUNICATIONS_VIEW: 'communications.view',
  COMMUNICATIONS_SEND: 'communications.send',

  // Audit & settings
  AUDIT_VIEW: 'audit.view',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',

  // Platform governance (founder-only unless delegated explicitly)
  PLATFORM_CONFIGURATION: 'platform.configuration',
  SECURITY_CONFIGURATION: 'security.configuration',
  ROLE_SYSTEM_MANAGE: 'role.system.manage',
  FOUNDER_MANAGE: 'founder.manage',
  BACKUP_VIEW: 'backup.view',
  BACKUP_CREATE: 'backup.create',
  BACKUP_RESTORE_REQUEST: 'backup.restore.request',
  SECRET_MANAGE: 'secret.manage',
  OWNERSHIP_TRANSFER: 'ownership.transfer',

  // Internal economy (Economy & Security Closure)
  ECONOMY_TRANSACTION_VIEW: 'economy.transaction.view',
  ECONOMY_TRANSACTION_CREATE: 'economy.transaction.create',
  ECONOMY_REFUND: 'economy.refund',
  ECONOMY_ADJUST: 'economy.adjust',
  ECONOMY_REVERSAL: 'economy.reversal',
  ECONOMY_COMMISSION_VIEW: 'economy.commission.view',
  ECONOMY_LEDGER_VIEW: 'economy.ledger.view',
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];

/**
 * Default capabilities per ORGANIZATION role.
 * Scope: ORGANIZATION by default (can be narrowed at assignment).
 */
export const ORGANIZATION_ROLE_CAPABILITIES: Record<OrganizationRole, Capability[]> = {
  ORG_OWNER: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.ORGANIZATION_UPDATE,
    CAPABILITIES.MEMBERS_VIEW,
    CAPABILITIES.MEMBERS_INVITE,
    CAPABILITIES.MEMBERS_UPDATE,
    CAPABILITIES.MEMBERS_REMOVE,
    CAPABILITIES.ROLES_VIEW,
    CAPABILITIES.ROLES_MANAGE,
    CAPABILITIES.COURSES_VIEW,
    CAPABILITIES.COURSES_MANAGE,
    CAPABILITIES.PROGRAMS_VIEW,
    CAPABILITIES.PROGRAMS_MANAGE,
    CAPABILITIES.REPORTS_VIEW,
    CAPABILITIES.REPORTS_EXPORT,
    CAPABILITIES.BOOKINGS_VIEW,
    CAPABILITIES.BOOKINGS_MANAGE,
    CAPABILITIES.CONTENT_VIEW,
    CAPABILITIES.CONTENT_MANAGE,
    CAPABILITIES.CONTENT_PUBLISH,
    CAPABILITIES.COMMUNICATIONS_VIEW,
    CAPABILITIES.COMMUNICATIONS_SEND,
    CAPABILITIES.AUDIT_VIEW,
    CAPABILITIES.SETTINGS_VIEW,
    CAPABILITIES.SETTINGS_MANAGE,
    // Organization-scoped economy visibility (read-only; never platform-wide)
    CAPABILITIES.ECONOMY_TRANSACTION_VIEW,
    CAPABILITIES.ECONOMY_LEDGER_VIEW,
  ],
  ORG_ADMIN: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.MEMBERS_VIEW,
    CAPABILITIES.MEMBERS_INVITE,
    CAPABILITIES.MEMBERS_UPDATE,
    CAPABILITIES.MEMBERS_REMOVE,
    CAPABILITIES.ROLES_VIEW,
    CAPABILITIES.ROLES_MANAGE,
    CAPABILITIES.COURSES_VIEW,
    CAPABILITIES.COURSES_MANAGE,
    CAPABILITIES.PROGRAMS_VIEW,
    CAPABILITIES.PROGRAMS_MANAGE,
    CAPABILITIES.REPORTS_VIEW,
    CAPABILITIES.REPORTS_EXPORT,
    CAPABILITIES.BOOKINGS_VIEW,
    CAPABILITIES.BOOKINGS_MANAGE,
    CAPABILITIES.CONTENT_VIEW,
    CAPABILITIES.CONTENT_MANAGE,
    CAPABILITIES.COMMUNICATIONS_VIEW,
    CAPABILITIES.COMMUNICATIONS_SEND,
    CAPABILITIES.AUDIT_VIEW,
    CAPABILITIES.SETTINGS_VIEW,
    // Organization-scoped economy visibility (read-only)
    CAPABILITIES.ECONOMY_TRANSACTION_VIEW,
    CAPABILITIES.ECONOMY_LEDGER_VIEW,
  ],
  ORG_MANAGER: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.MEMBERS_VIEW,
    CAPABILITIES.COURSES_VIEW,
    CAPABILITIES.COURSES_MANAGE,
    CAPABILITIES.PROGRAMS_VIEW,
    CAPABILITIES.PROGRAMS_MANAGE,
    CAPABILITIES.REPORTS_VIEW,
    CAPABILITIES.BOOKINGS_VIEW,
    CAPABILITIES.BOOKINGS_MANAGE,
    CAPABILITIES.CONTENT_VIEW,
    CAPABILITIES.COMMUNICATIONS_VIEW,
    CAPABILITIES.SETTINGS_VIEW,
  ],
  ORG_STAFF: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.MEMBERS_VIEW,
    CAPABILITIES.COURSES_VIEW,
    CAPABILITIES.PROGRAMS_VIEW,
    CAPABILITIES.REPORTS_VIEW,
    CAPABILITIES.BOOKINGS_VIEW,
    CAPABILITIES.CONTENT_VIEW,
    CAPABILITIES.COMMUNICATIONS_VIEW,
  ],
  ORG_MEMBER: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.COURSES_VIEW,
    CAPABILITIES.PROGRAMS_VIEW,
    CAPABILITIES.BOOKINGS_VIEW,
  ],
};

/**
 * Platform roles mapped to capabilities (SELF + PLATFORM scope where applicable).
 * These are additive to organization capabilities.
 */
export const PLATFORM_ROLE_CAPABILITIES: Partial<Record<UserRole, Capability[]>> = {
  // LEARNER/EDUCATOR access their own resources via SELF-scope ownership checks
  // (authorize() grants BOOKINGS_VIEW/COURSES_VIEW/VERIFICATION_VIEW on self).
  LEARNER: [],
  EDUCATOR: [],
  LAJNAH_VERIFIER: [CAPABILITIES.VERIFICATION_VIEW, CAPABILITIES.VERIFICATION_MANAGE, CAPABILITIES.AUDIT_VIEW],
  FOUNDER_ADMIN: [
    CAPABILITIES.ORGANIZATION_VIEW,
    CAPABILITIES.MEMBERS_VIEW,
    CAPABILITIES.ROLES_VIEW,
    CAPABILITIES.REPORTS_VIEW,
    CAPABILITIES.BOOKINGS_VIEW,
    CAPABILITIES.VERIFICATION_VIEW,
    CAPABILITIES.VERIFICATION_MANAGE,
    CAPABILITIES.AUDIT_VIEW,
    CAPABILITIES.PLATFORM_CONFIGURATION,
    CAPABILITIES.SECURITY_CONFIGURATION,
    CAPABILITIES.ROLE_SYSTEM_MANAGE,
    CAPABILITIES.FOUNDER_MANAGE,
    CAPABILITIES.BACKUP_VIEW,
    CAPABILITIES.BACKUP_CREATE,
    CAPABILITIES.BACKUP_RESTORE_REQUEST,
    CAPABILITIES.SECRET_MANAGE,
    CAPABILITIES.OWNERSHIP_TRANSFER,
    CAPABILITIES.SETTINGS_VIEW,
    CAPABILITIES.SETTINGS_MANAGE,
    CAPABILITIES.CONTENT_VIEW,
    CAPABILITIES.CONTENT_MANAGE,
    CAPABILITIES.CONTENT_PUBLISH,
    CAPABILITIES.COMMUNICATIONS_VIEW,
    CAPABILITIES.COMMUNICATIONS_SEND,
    // Internal economy — founder observe/control/audit
    CAPABILITIES.ECONOMY_TRANSACTION_VIEW,
    CAPABILITIES.ECONOMY_TRANSACTION_CREATE,
    CAPABILITIES.ECONOMY_REFUND,
    CAPABILITIES.ECONOMY_ADJUST,
    CAPABILITIES.ECONOMY_REVERSAL,
    CAPABILITIES.ECONOMY_COMMISSION_VIEW,
    CAPABILITIES.ECONOMY_LEDGER_VIEW,
  ],
};
